# Project ArtX
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="ARTX"
ORG_DBA="ARTX TOKEN"
ORG_URL="https://artx.one"
ORG_LOGO = "https://artx.one/artx.png"

[[CURRENCIES]]
code = "ARTX"
name = "ARTX TOKEN"
issuer = "GDUXTG33DLNMAPYCV4VLQKTTPHATFAZPEID5EFP3NYUILP3P7U62JZOM"
is_asset_anchored = false
display_decimals = 2
desc="ARTX Token (ARTX) is ArtX NFT's native token. Learn more about ARTX NFT and ARTX Token at https://artx.one"
image="https://artx.one/artx.png"
conditions="There will only ever be 10 billion ARTX tokens in existence."
