# Project ArtX
VERSION="2.0.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="ARTX"
ORG_DBA="ARTX"
ORG_URL="https://artx.one"
ORG_LOGO="https://artx.one/artx.png"

[[CURRENCIES]]
code="ARTX"
name="ARTX"
issuer="GDUXTG33DLNMAPYCV4VLQKTTPHATFAZPEID5EFP3NYUILP3P7U62JZOM"
desc="ARTX Token is a utility token for ArtX NFT. Learn more about ArtX NFT at https://artx.one"
display_decimals=2
image="https://artx.one/artx.png"
conditions="There will only ever be 10 billion ARTX tokens in existence."
status="live"
is_asset_anchored=false
fixed_number=10000000000

[[CURRENCIES]]
code="ARTPAY"
name="ARTPAY"
issuer="GCE7CSG4D6UN3TLRTUI6DGLBX4OV5LJW42CIQSMGHKNVFKW6PS2CSNAN"
desc="ARTPAY is a stablecoin for ArtX NFT. Learn more about ArtX NFT at https://artx.one"
display_decimals=2
image="https://artx.one/artx.png"
conditions="1 ARTPAY = 1000000 ARTX."
status="live"
is_asset_anchored=true
anchor_asset_type="crypto"
anchor_asset="ARTX"
