# Project ArtX
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="ARTX"
ORG_DBA="ARTX TOKEN"
ORG_URL="https://artx.one"
ORG_LOGO = "https://artx.one/artx.png"

ACCOUNTS=[
"GDB4C44N6HWBOPP5RAO6PTDRZ4FQZV25AVHAFZX7LZNFWHVLTF75SOMY",
"GDUXTG33DLNMAPYCV4VLQKTTPHATFAZPEID5EFP3NYUILP3P7U62JZOM",
"GB6A5X4I6FKETGJLMNESQCN75NWW2T6EMWBPJMSD6YH63OWMTE4NKOYM"
]

[[CURRENCIES]]
code = "ARTX"
name = "ARTX TOKEN"
issuer = "GDUXTG33DLNMAPYCV4VLQKTTPHATFAZPEID5EFP3NYUILP3P7U62JZOM"
is_asset_anchored = false
display_decimals = 2
desc="ARTX Token is a utility token for ArtX NFT. Learn more about ArtX NFT and ARTX Token at https://artx.one"
image="https://artx.one/artx.png"
conditions="There will only ever be 10 billion ARTX tokens in existence."
